---

- name: Ensure WebTrees Home paths exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ webtrees_uid }}"
    group: "{{ webtrees_gid }}"
    mode: "{{ item.mode }}"
  with_items:
    - path: "{{ webtrees_data_path }}"
      mode: "0750"
    - path: "{{ webtrees_config_path }}"
      mode: "0750"
    - path: "{{ webtrees_log_path }}"
      mode: "0750"

- name: Ensure WebTrees support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ webtrees_base_path }}/{{ item }}"
    mode: 0640
    owner: "{{ webtrees_uid }}"
    group: "{{ webtrees_gid }}"
  with_items:
    - env
    - labels

- name: Ensure WebTrees container image is pulled
  community.docker.docker_image:
    name: "{{ webtrees_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ webtrees_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else webtrees_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure WebTrees container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ webtrees_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure WebTrees container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ webtrees_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure WebTrees systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/webtrees.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ webtrees_identifier }}.service"
